// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlioj-1Zcon0y7mH5x7AhCm0kWs19oxQc',
    appId: '1:49369084718:web:93eb9f1225e7e425ba80bf',
    messagingSenderId: '49369084718',
    projectId: 'go-cut-vendor-cbbdb',
    authDomain: 'go-cut-vendor-cbbdb.firebaseapp.com',
    storageBucket: 'go-cut-vendor-cbbdb.firebasestorage.app',
    measurementId: 'G-1Y4THT7F8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsQ7V7r0M9YgCT3qrJFz24J7cEFdWuo44',
    appId: '1:49369084718:android:21eaa5a034aef2e2ba80bf',
    messagingSenderId: '49369084718',
    projectId: 'go-cut-vendor-cbbdb',
    storageBucket: 'go-cut-vendor-cbbdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjB7GCYbew2aXoQHv84ZHcLugpjJcOpyM',
    appId: '1:49369084718:ios:0d88ea12a396c6eeba80bf',
    messagingSenderId: '49369084718',
    projectId: 'go-cut-vendor-cbbdb',
    storageBucket: 'go-cut-vendor-cbbdb.firebasestorage.app',
    androidClientId: '49369084718-v1mcr2nul0llo3c52sbitog3euovbj0n.apps.googleusercontent.com',
    iosClientId: '49369084718-88gk7mjgq7jj75pet9oeund2fqpd9doq.apps.googleusercontent.com',
    iosBundleId: 'com.digitalraiz.govendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjB7GCYbew2aXoQHv84ZHcLugpjJcOpyM',
    appId: '1:49369084718:ios:f43b7ed6caa46285ba80bf',
    messagingSenderId: '49369084718',
    projectId: 'go-cut-vendor-cbbdb',
    storageBucket: 'go-cut-vendor-cbbdb.firebasestorage.app',
    androidClientId: '49369084718-v1mcr2nul0llo3c52sbitog3euovbj0n.apps.googleusercontent.com',
    iosClientId: '49369084718-3dgkm4as78c7qqrl68vhp883pp80qmpc.apps.googleusercontent.com',
    iosBundleId: 'com.digitalraiz.gocutVendor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlioj-1Zcon0y7mH5x7AhCm0kWs19oxQc',
    appId: '1:49369084718:web:926245255d5eeca3ba80bf',
    messagingSenderId: '49369084718',
    projectId: 'go-cut-vendor-cbbdb',
    authDomain: 'go-cut-vendor-cbbdb.firebaseapp.com',
    storageBucket: 'go-cut-vendor-cbbdb.firebasestorage.app',
    measurementId: 'G-LXW3Z74RWT',
  );
}
